name: Faith Center San Fernando
favicon: null
layout_spectrum: 0.08932933397591114
typography_spectrum: 0.7830989356152713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2510998642537743
  lightness: 0.523798116017133
  saturation: 0.9748790024314076
  rhythmicContrast: 0.028103662189096212
purpose: []
