name: Faith Center San Fernando
favicon: null
layout_spectrum: 0.34067
typography_spectrum: 0.7830989356152713
title: 'Cultivating Authentic Faith, Hope and Love'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9343a'
    - '#bebebe'
    - '#2c2c2c'
    - '#c68283'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
